spring:
  application:
    name: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Prometheus
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application: test
  endpoint:
    prometheus:
      access: unrestricted
